admin_channels: []
admin_role: Admin
alert_channel_id: 'ChannelID'
alert_threshold: 500
corporation_id: 'CORPID'
discord_bot_token: BOT-Token
eve_online_callback_url: http://localhost:5005/oauth-callback
eve_online_client_id: CLIENTID
eve_online_secret_key: SECRETKEY
metenox_moon_drill_ids: []
